###########################
# storage class
###########################
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: testproject-sc
provisioner: file.csi.azure.com
volumeBindingMode: Immediate
reclaimPolicy: Retain